import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
import { useAuth } from '@/lib/AuthContext';
import { TrendingUp, Network, Gift, WalletCards, ArrowDownToLine, UserRound, ArrowUpRight } from 'lucide-react';
import MetricCard from '@/components/wealth/MetricCard';
import PageHeader from '@/components/wealth/PageHeader';
import StatusPill from '@/components/wealth/StatusPill';
import FinancialNotice from '@/components/wealth/FinancialNotice';

const money=n=>`R ${Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export default function Dashboard(){
 const {user}=useAuth(); const [data,setData]=useState(null);
 useEffect(()=>{if(!user)return; Promise.all([base44.entities.Investment.filter({member_id:user.id}),base44.entities.Incentive.filter({member_id:user.id}),base44.entities.WalletTransaction.filter({member_id:user.id}),base44.entities.Withdrawal.filter({member_id:user.id}),base44.entities.ReferralRelationship.filter({referrer_user_id:user.id}),base44.entities.IncentiveConfiguration.list('-updated_date',1)]).then(([investments,incentives,ledger,withdrawals,refs,configs])=>setData({investments,incentives,ledger,withdrawals,refs,config:configs[0]}));},[user]);
 if(!data)return <div className="grid min-h-[60vh] place-items-center"><div className="h-8 w-8 animate-spin rounded-full border-2 border-slate-700 border-t-[#d4af37]"/></div>;
 const active=data.investments.filter(i=>['ACTIVE','PAYMENT_RECEIVED'].includes(i.investment_status)); const total=active.reduce((s,i)=>s+Number(i.zar_equivalent),0); const available=data.ledger.filter(x=>x.balance_type==='AVAILABLE_REWARD'&&x.status==='POSTED').reduce((s,x)=>s+(x.type==='CREDIT'||x.type==='RELEASE'?Number(x.amount):-Number(x.amount)),0); const pending=data.incentives.filter(x=>['PENDING','UNDER_REVIEW','APPROVED'].includes(x.status)).reduce((s,x)=>s+Number(x.amount),0); const earned=data.incentives.filter(x=>['AVAILABLE','PAID'].includes(x.status)).reduce((s,x)=>s+Number(x.amount),0); const withdrawn=data.withdrawals.filter(x=>x.status==='PAID').reduce((s,x)=>s+Number(x.amount),0); const target=data.config?.qualification_requirement||10; const qualified=data.refs.filter(x=>x.is_qualified).length;
 const actions=[['INVEST','/investments',TrendingUp],['MY NETWORK','/network',Network],['MY REWARDS','/wallet',Gift],['MY WALLET','/wallet',WalletCards],['WITHDRAW','/wallet',ArrowDownToLine],['PROFILE','/profile',UserRound]];
 return <><PageHeader eyebrow="Member command centre" title={`Good day, ${(user?.full_name||'Member').split(' ')[0]}`} description="Your verified financial, partner and compliance position in one view." action={<StatusPill value={user?.kyc_status||'PENDING'}/>}/><FinancialNotice>Investment outcomes and exchange rates may vary. Product terms, risk disclosures and eligibility controls apply before confirmation.</FinancialNotice><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Total investment" value={money(total)}/><MetricCard label="Current investment value" value={money(total)} detail="Based on recorded transaction values" tone="blue"/><MetricCard label="Available partner rewards" value={money(available)}/><MetricCard label="Pending rewards" value={money(pending)} tone="amber"/><MetricCard label="Total rewards earned" value={money(earned)}/><MetricCard label="Total withdrawn" value={money(withdrawn)} tone="blue"/><MetricCard label="Direct introductions" value={data.refs.length}/><MetricCard label="Total network members" value={data.refs.length} detail="Level 1 and permitted leadership view"/></div><div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{actions.map(([label,to,Icon])=><Link key={label} to={to} className="group rounded-2xl border border-white/10 bg-[#0b1525] p-4 transition hover:-translate-y-0.5 hover:border-[#c5a059]/30"><div className="flex items-start justify-between"><Icon className="h-5 w-5 text-[#d4af37]"/><ArrowUpRight className="h-4 w-4 text-slate-600 group-hover:text-[#d4af37]"/></div><p className="mt-7 text-xs font-semibold tracking-wide text-slate-200">{label}</p></Link>)}</div></>;
}